@startuml

' avoid problems with angled crows feet
skinparam linetype ortho

interface BookRepository
interface BookTicketRepository
BookRepository <|.- InMemoryBookRepository
BookTicketRepository <|.- InMemoryBookTicketRepository

LibraryService *-- InMemoryBookRepository
LibraryService *-- InMemoryBookTicketRepository

hide empty members

@enduml