package tictactoe.exception;

public enum GameExceptionType {
    WORDS_INSTEAD_COORDINATES_INPUTTED,
    COORDINATE_IS_NOT_IN_INTERVAL,
    COORDINATE_IS_BUSY,
    UNKNOWN_PLAYER_TYPE,
    BAD_PARAMETERS
}
